### ISSUE TITLE
Could not find gem 'middleman-deploy (>= 0) ruby' in git://github.com/LeonB/middleman-backtick.git (at master). Source does not contain any versions of 'middleman-deploy (>= 0) ruby'

### ISSUE THREAD

**Issue by rafaelhaertel** [LeonB/middleman-backtick#3]
I get this error when i run bundle install. Can you tell me why? I'm using middleman 3.1.0.rc.2

**Comment by LeonB** [comment]
Sorry for the late reply. I don't think this is a problem of middleman-backtick but a problem with your Gemfile in your projects root. I'm going to close this issue for now. If you think I'm wrong you can reopen it. Please attach a testcase if you reopen it.
